# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43e748194f740caec366e1e940688dce1a7293b6f4cf383a4107451bc45d1377b35477a7c35207b6118ab31d8cb282e2df87ae89301b7eaf10be4b063b4508c2

test:
  secret_key_base: 9e8d01b33f20c1390847a3afdb3cc6b682b3e5f0bbcb0cc39c6178007de4c225746c2bd044a2f9f39a4337110dd50283abdee4371351ebc44cf3ef5897e4861a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
